//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TonerManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StockLocation
    {
        public int stockLocationId { get; set; }
        public int customerId { get; set; }
        public string stockLocationName { get; set; }
        public string stockLocationAddress { get; set; }
        public string stockLocationContactNumber { get; set; }
    }
}
