//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TonerManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserCustomer
    {
        public int userCustomerID { get; set; }
        public int userID { get; set; }
        public int customerID { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual User User { get; set; }
    }
}
