//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TonerManagement
{
    using System;
    using System.Collections.Generic;
    
    public partial class TonerPrinter
    {
        public int tonerPrinterId { get; set; }
        public int printerId { get; set; }
        public int tonerId { get; set; }
        public System.DateTime timestamp { get; set; }
        public int tonerPercentage { get; set; }
        public int tonerExpectedYield { get; set; }
        public int totalPagesPrinted { get; set; }
        public int tonerBottelsChanged { get; set; }
        public int nominalCoverage { get; set; }
    
        public virtual Printer Printer { get; set; }
        public virtual Toner Toner { get; set; }
    }
}
