//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TonerManagement
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TonerManagementEntities : DbContext
    {
        public TonerManagementEntities()
            : base("name=TonerManagementEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Customer> Customers { get; set; }
        public virtual DbSet<Printer> Printers { get; set; }
        public virtual DbSet<StockLocation> StockLocations { get; set; }
        public virtual DbSet<StockLocationToner> StockLocationToners { get; set; }
        public virtual DbSet<Toner> Toners { get; set; }
        public virtual DbSet<TonerPrinter> TonerPrinters { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<UserCustomer> UserCustomers { get; set; }
    }
}
