//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TonerManagement
{
    using System;
    using System.Collections.Generic;
    
    public partial class Toner
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Toner()
        {
            this.StockLocationToners = new HashSet<StockLocationToner>();
            this.TonerPrinters = new HashSet<TonerPrinter>();
        }
    
        public int tonerId { get; set; }
        public string tonerCode { get; set; }
        public string tonerName { get; set; }
        public bool isCyan { get; set; }
        public bool isYellow { get; set; }
        public bool isMagenta { get; set; }
        public bool isKeying { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StockLocationToner> StockLocationToners { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TonerPrinter> TonerPrinters { get; set; }
    }
}
